WIP: Add area/metering label.
kubesphere/prow-tutorial pull request #33
Opened 2021-04-15 10:01 UTC by yunkunrao

Signed-off-by: Rao Yunkun <yunkunrao@yunify.com>

2021-04-15 10:01 UTC, yunkunrao commented
/cc LinuxSuRen

2021-04-15 11:09 UTC, LinuxSuRen requested changes
Not only this repository `kubesphere/kubesphere` needs this label. For example: `console`, `ks-installer`, `website`.

And I'm wondering if you can post a screenshot to show the color of this label.

2021-04-16 01:56 UTC, yunkunrao commented
Currently metering related repos are as follows in my opinion:

- kubesphere/kubesphere
- kubesphere/console
- kubesphere/ks-installer
- kubesphere/community
- kubesphere/website

@LinuxSuRen can we add metering labels for above repos currently, and add more  repos when it's needed? If it's ok, I will update this pr.

2021-04-16 02:09 UTC, LinuxSuRen commented
I prefer adding them to this PR.

2021-04-16 08:45 UTC, yunkunrao commented
got it

2021-04-16 08:53 UTC, yunkunrao commented
> Not only this repository `kubesphere/kubesphere` needs this label. For example: `console`, `ks-installer`, `website`.
> 
> And I'm wondering if you can post a screenshot to show the color of this label.

Yeah, got it.

![Uploading image.png…]()

2021-04-16 09:04 UTC, LinuxSuRen commented on ks-ci-bot/labels.yaml
> +      - color: A050cc
Please make sure all characters are lower-case.

2021-04-20 07:45 UTC, LinuxSuRen approved these changes
/lgtm

2021-04-21 05:55 UTC, yunkunrao commented
/cc zryfish

2021-04-23 06:16 UTC, zryfish commented
/approve

2021-04-23 06:16 UTC, merged